# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{happy-nav}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Pearson"]
  s.date = %q{2010-12-26}
  s.description = %q{Happy Nav is the easy (and cheerful) way to create structured HTML for your site navigation.}
  s.email = %q{andy@andy-pearson.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/happy-nav.rb",
     "lib/happy-nav/navigation_presenter.rb",
     "lib/happy-nav/railtie.rb",
     "rails/init.rb",
     "spec/navigation_helper_spec.rb",
     "spec/navigation_presenter_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/andypearson/happy-nav}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Happy Nav is the easy (and cheerful) way to create structured HTML for your site navigation.}
  s.test_files = [
    "spec/navigation_helper_spec.rb",
     "spec/navigation_presenter_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

